services:

  trips:
    build:
      context: ./services/trips
    env_file:
      - storage.env
    ports:
      - "8000:8000"
    depends_on:
      - database

  gear:
    build:
      context: ./services/gear
    env_file:
      - storage.env
    ports:
      - "8001:8000"
    depends_on:
      - database

  reminders:
    build:
      context: ./services/reminders
    env_file:
      - storage.env
    ports:
      - "8002:8000"
    depends_on:
      - trips
      - gear

  database:
    image: postgres:17
    env_file:
      - storage.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: